apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 30Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/priya/may21/esdata/springboot"
  persistentVolumeReclaimPolicy: Retain