prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'springbootscrape'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
          #- targets: ['172.17.0.4:8080']
          - targets: ['person.com:80']
# extraScrapeConfigs: |
#   - job_name: 'spring boot scrape'
#     metrics_path: '/actuator/prometheus'
#     scrape_interval: 5s
#     static_configs:
#       - targets: ['localhost:8080']
# scrape_configs:
#   - job_name: 'spring boot scrape'
#     metrics_path: '/actuator/prometheus'
#     scrape_interval: 5s
#     static_configs:
#       - targets: ['localhost:8080']